server:
  port: 9094
  servlet:
    context-path: /settlement

spring:
  application:
    name: coupon-settlement
eureka:
  client:
    service-url:
      defaultZone: http://server1:9090/eureka/
logging:
  level:
    com.imooc.coupon: debug